#ifndef ESTADOS_HPP
#define ESTADOS_HPP

// define os estados do pacote
enum Estados
{
    NAO_POSTADO,
    CHEGADA_ESCALONADA_ARMAZEM,
    CHEGADA_NAO_ARMAZENADO,
    ARMAZENADO_ARMAZEM,
    ALOCADO_TRANSPORTE,
    ENTREGUE
};

#endif /* ESTADOS_HPP */